#!/bin/sh

set -e

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

getTokenForSA() {
  SERVICEACCOUNT=${1}
  SECRET_NAME=$( kubectl get serviceaccount -n ${SPI_NAMESPACE} ${SERVICEACCOUNT} -o json | jq -r '.secrets[].name' )
  TOKEN=$( kubectl get secret ${SECRET_NAME} -n ${SPI_NAMESPACE} -o json | jq -r '.data.token' )
  echo ${TOKEN} | base64 -d
}

getTokenForSA "spi-controller-manager" > /tmp/spi-operator-sa-token
getTokenForSA "spi-oauth-sa" > /tmp/spi-oauth-sa-token
