#!/bin/sh

# set -x

TOKEN_FILE=$( realpath ~/.kube/cache/oidc-login/* )

if [ -z ${TOKEN_FILE} ] || [ ! -f ${TOKEN_FILE} ]; then
  echo "file does not exist"
  exit 1
fi

cat ${TOKEN_FILE} | jq -r '.id_token'
