#!/bin/bash

. "$( dirname "${0}" )/env.sh"

# set -x

until oc login --insecure-skip-tls-verify=true -u ${OPENSHIFT_ADMIN_USER} -p ${OPENSHIFT_ADMIN_PASS} ${OPENSHIFT_CLUSTER_URL}; do
  sleep 10
done
