#!/bin/sh

set -e

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

pushd ${SPIOAUTHDIR}

TAG=$( getBranch )

IMAGE="${SPIOAUTHIMAGE}:${TAG}"

make docker-build docker-push SPIS_IMG=${IMAGE}

popd
