#!/bin/sh

set -e

# shellcheck source=env.sh
. "$( dirname "${0}" )/env.sh"

getTokenForSA() {
  SERVICEACCOUNT=${1}
  TOKEN=$( kubectl create token ${SERVICEACCOUNT} -n ${SPI_NAMESPACE} )
  echo ${TOKEN}
}

getTokenForSA "spi-controller-manager" > /tmp/spi-operator-sa-token
getTokenForSA "spi-oauth-sa" > /tmp/spi-oauth-sa-token
